const data = [
    {
        "caliber": "Dummy Caliber 1",
        "types": [
            {
                "name": "Dummy Type 1",
                "PenetrationPower": "5",
                "ArmorDamage": "2",
                "ProjectileCount": "3",
                "Damage": "10",
                "InitialSpeed": "100",
                "RicochetChance": "0.1",
                "FragmentationChance": "0.1",
                "BulletMassGram": "1",
                "HeavyBleedingDelta": "0.1",
                "LightBleedingDelta": "0.1",
                "ammoAccr": "5",
                "ammoHear": "5",
                "ammoRec": "5",
                "MalfMisfireChance": "0.01",
                "MisfireChance": "0.01",
                "MalfFeedChance": "0.01",
                "DurabilityBurnModificator": "1",
                "HeatFactor": "1"
            },
            {
                "name": "Dummy Type 2",
                "PenetrationPower": "10",
                "ArmorDamage": "3",
                "ProjectileCount": "6",
                "Damage": "20",
                "InitialSpeed": "150",
                "RicochetChance": "0.2",
                "FragmentationChance": "0.2",
                "BulletMassGram": "2",
                "HeavyBleedingDelta": "0.2",
                "LightBleedingDelta": "0.2",
                "ammoAccr": "10",
                "ammoHear": "10",
                "ammoRec": "10",
                "MalfMisfireChance": "0.02",
                "MisfireChance": "0.02",
                "MalfFeedChance": "0.02",
                "DurabilityBurnModificator": "2",
                "HeatFactor": "2"
            }
        ]
    },
    {
        "caliber": "Dummy Caliber 2",
        "types": [
            {
                "name": "Dummy Type A",
                "PenetrationPower": "15",
                "ArmorDamage": "4",
                "ProjectileCount": "9",
                "Damage": "30",
                "InitialSpeed": "200",
                "RicochetChance": "0.3",
                "FragmentationChance": "0.3",
                "BulletMassGram": "3",
                "HeavyBleedingDelta": "0.3",
                "LightBleedingDelta": "0.3",
                "ammoAccr": "15",
                "ammoHear": "15",
                "ammoRec": "15",
                "MalfMisfireChance": "0.03",
                "MisfireChance": "0.03",
                "MalfFeedChance": "0.03",
                "DurabilityBurnModificator": "3",
                "HeatFactor": "3"
            },
            {
                "name": "Dummy Type B",
                "PenetrationPower": "20",
                "ArmorDamage": "5",
                "ProjectileCount": "12",
                "Damage": "40",
                "InitialSpeed": "250",
                "RicochetChance": "0.4",
                "FragmentationChance": "0.4",
                "BulletMassGram": "4",
                "HeavyBleedingDelta": "0.4",
                "LightBleedingDelta": "0.4",
                "ammoAccr": "20",
                "ammoHear": "20",
                "ammoRec": "20",
                "MalfMisfireChance": "0.04",
                "MisfireChance": "0.04",
                "MalfFeedChance": "0.04",
                "DurabilityBurnModificator": "4",
                "HeatFactor": "4"
            }
        ]
    },
    {
        "caliber": "Dummy Caliber 3",
        "types": [
            {
                "name": "Dummy Type X",
                "PenetrationPower": "25",
                "ArmorDamage": "6",
                "ProjectileCount": "15",
                "Damage": "50",
                "InitialSpeed": "300",
                "RicochetChance": "0.5",
                "FragmentationChance": "0.5",
                "BulletMassGram": "5",
                "HeavyBleedingDelta": "0.5",
                "LightBleedingDelta": "0.5",
                "ammoAccr": "25",
                "ammoHear": "25",
                "ammoRec": "25",
                "MalfMisfireChance": "0.05",
                "MisfireChance": "0.05",
                "MalfFeedChance": "0.05",
                "DurabilityBurnModificator": "5",
                "HeatFactor": "5"
            },
            {
                "name": "Dummy Type Y",
                "PenetrationPower": "30",
                "ArmorDamage": "7",
                "ProjectileCount": "18",
                "Damage": "60",
                "InitialSpeed": "350",
                "RicochetChance": "0.6",
                "FragmentationChance": "0.6",
                "BulletMassGram": "6",
                "HeavyBleedingDelta": "0.6",
                "LightBleedingDelta": "0.6",
                "ammoAccr": "30",
                "ammoHear": "30",
                "ammoRec": "30",
                "MalfMisfireChance": "0.06",
                "MisfireChance": "0.06",
                "MalfFeedChance": "0.06",
                "DurabilityBurnModificator": "6",
                "HeatFactor": "6"
            }
        ]
    }
];
